__title__ = 'hashnode_py'
__package_name__ = 'hashnode_py'
__version__ = '0.0.10'
__description__ = "Hashnode_Py, The python client to interact with hashnode graphql api"
__email__ = "talaat049@gmail.com"
__author__ = 'Talaat Hasanin'
__github__ = 'https://github.com/TalaatHasanin/hashnode_py'
__pypi__ = ''
__license__ = 'MIT'
__copyright__ = 'Copyright (C) 2024  Talaat Hasanin'
